services:
  - type: web
    name: lumen-ecommerce
    env: node
    plan: free
    rootDir: template
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: "file:./prisma/dev.db"
      - key: ADMIN_PASSWORD
        value: admin2026
      - key: ADMIN_TOKEN
        value: admin_secret_token_2026
      - key: SESSION_SECRET
        generateValue: true
